version: '3'
services:
  chromadb:
    image: chromadb/chroma
    ports:
      - '8000:8000'
    volumes:
      - ./.chromadb:/chroma/chroma
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_USER: codellm
      POSTGRES_PASSWORD: password
      POSTGRES_DB: codellm
    ports:
      - '5432:5432'
    volumes:
      - ./.postgres:/var/lib/postgresql/data
