debugLevel: debug
llms:
  embedding:
    provider: ollama
    model: nomic-embed-text
  summarization:
    provider: ollama
    model: mixtral:8x7b
  agent:
    provider: ollama
    model: mixtral:8x7b
  # agent:
  #   provider: openai
  #   model: gpt-4-turbo-preview

providers:
  openai:
    apiKey: ''
  ollama:
    host: 'http://localhost:11434'
